version: "3.7"
x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    - AIRFLOW__CORE__DAGS_FOLDER=/usr/local/airflow/dags
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__LOGGING_LEVEL=WARN
    - AIRFLOW_CONN_CLICKHOUSE_DEFAULT=http://default:@clickhouse-server:9000
  volumes:
    - ./airflow/requirements.txt:/requirements.txt
    - ./airflow/dags:/usr/local/airflow/dags
    - ./airflow/scripts:/usr/local/airflow/scripts

services:
  # clickhouse:
  clickhouse-server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"
    volumes:
      - ./data/:/var/lib/clickhouse/user_files/data/
  client:
    image: yandex/clickhouse-server
    command: ['--host', 'server']
  # airflow:
  postgres:
    image: postgres:13.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=airflow
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    logging:
      options:
        max-size: 10m
        max-file: "3"

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create --firstname airflow --lastname airflow --email airflow --password airflow --username airflow --role Admin"
    restart: on-failure
    depends_on:
      - postgres

  airflow-webserver:
    <<: *airflow-common
    command: airflow webserver
    ports:
      - 8080:8080
    container_name: airflow_webserver
    restart: always
    depends_on:
      - airflow-init

  airflow-scheduler:
      <<: *airflow-common
      command: airflow scheduler
      container_name: airflow_scheduler
      deploy:
        restart_policy:
          condition: on-failure
          delay: 8s
          max_attempts: 3
      depends_on:
        - airflow-init